module SchwabRb::Orders::Duration
  DAY = "DAY"
  GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"
  FILL_OR_KILL = "FILL_OR_KILL"
  IMMEDIATE_OR_CANCEL = "IMMEDIATE_OR_CANCEL"
  END_OF_WEEK = "END_OF_WEEK"
  END_OF_MONTH = "END_OF_MONTH"
  NEXT_END_OF_MONTH = "NEXT_END_OF_MONTH"
end
